### ISSUE TITLE
Error code 2503

### ISSUE THREAD

**Issue by codeboxqc** [deepak-rathi/VS2017OfflineSetupUtility#16] opened 2022-09-19 22:50 UTC
does not start give me error 2503 i have vs2017 and 2019

**Comment by codeboxqc** [comment] 2022-09-19 22:51
![Untitled](https://user-images.githubusercontent.com/28874037/191133023-9646a9c7-8f40-474f-a72a-cfa1f153decb.jpg)

error

**Comment by deepak-rathi** [comment] 2022-09-20 16:49
I understand that the Windows installer crashed while installing the app with the error code 2503. I would suggest you check if there are any pending PC/system restarts due to new software installation or Windows updates.

I verified the released installer in Windows Sandbox and was not able to reproduce this error.

**Closed** 2022-10-02 13:05 UTC
